package com.model;

/**
 * TShou generated by MyEclipse Persistence Tools
 */

/**
 * @author Administrator
 *
 */
public class TShou implements java.io.Serializable
{

	private Integer id;
	private Integer userId;
	private String xileixing;
	private String yiwuleixing;

	private Float jiage;
	private String pinpai;
	private String yanse;
	private String beizhu;

	private String shoushi;
	private String lingshi;
	
	public String getBeizhu()
	{
		return beizhu;
	}
	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	
	public Float getJiage()
	{
		return jiage;
	}
	public void setJiage(Float jiage)
	{
		this.jiage = jiage;
	}
	public String getLingshi()
	{
		return lingshi;
	}
	public void setLingshi(String lingshi)
	{
		this.lingshi = lingshi;
	}
	public String getPinpai()
	{
		return pinpai;
	}
	public void setPinpai(String pinpai)
	{
		this.pinpai = pinpai;
	}
	public String getShoushi()
	{
		return shoushi;
	}
	public void setShoushi(String shoushi)
	{
		this.shoushi = shoushi;
	}
	public Integer getUserId()
	{
		return userId;
	}
	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}
	public String getXileixing()
	{
		return xileixing;
	}
	public void setXileixing(String xileixing)
	{
		this.xileixing = xileixing;
	}
	public String getYanse()
	{
		return yanse;
	}
	public void setYanse(String yanse)
	{
		this.yanse = yanse;
	}
	public String getYiwuleixing()
	{
		return yiwuleixing;
	}
	public void setYiwuleixing(String yiwuleixing)
	{
		this.yiwuleixing = yiwuleixing;
	}

}