package com.model;

/**
 * TXiyileixing generated by MyEclipse Persistence Tools
 */

public class TXiyileixing implements java.io.Serializable
{

	private Integer id;
	private String xileixing;
	private String yiwuleixing;
	private float jiage;
	
	
	
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public float getJiage()
	{
		return jiage;
	}
	public void setJiage(float jiage)
	{
		this.jiage = jiage;
	}
	
	public String getXileixing()
	{
		return xileixing;
	}
	public void setXileixing(String xileixing)
	{
		this.xileixing = xileixing;
	}
	public String getYiwuleixing()
	{
		return yiwuleixing;
	}
	public void setYiwuleixing(String yiwuleixing)
	{
		this.yiwuleixing = yiwuleixing;
	}

}